name: Python tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checks:
    name: Test and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Sync project dependencies
        run: uv sync --locked --dev

      - name: Run pre-commit checks
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest tests
